In [ ]:
import numpy as nm

In [ ]:
a=3
f=4
sum=a+f

In [ ]:
print(sum)

7


In [ ]:
x=nm.array([[1,2],[3,4]])
y=nm.array([[5,6],[7,8]])

In [ ]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(nm.dot(x,y),"\n")

[[19 22]
 [43 50]] 



In [ ]:
print(x.ndim)

NameError: ignored