<a href="https://colab.research.google.com/github/anushrijamar/Machine_learning/blob/main/lab1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [8]:
import numpy as nm

In [ ]:
a=3
f=4
sum=a+f

In [ ]:
print(sum)

7


In [ ]:
x=nm.array([[1,2],[3,4]])
y=nm.array([[5,6],[7,8]])

In [ ]:
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [ ]:
print(nm.dot(x,y),"\n")

[[19 22]
 [43 50]] 



In [7]:
print(x.ndim)

2
