<a href="https://colab.research.google.com/github/anushrijamar/Machine_learning/blob/main/tensorflow.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import tensorflow as tf

In [6]:
node1=tf.constant(3,dtype=tf.int32)
node2=tf.constant(8,dtype=tf.int32)
node3=tf.add(node1,node2)

In [7]:
import numpy as np

In [ ]:
array1=np.array([1,5,6,4])
print(array1)

In [9]:
array_2d=np.array([(7,4,1),(8,5,2),(9,6,3)])
print(array_2d)

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [10]:
array_2d[2][1]

6

In [11]:
print(array_2d)

[[7 4 1]
 [8 5 2]
 [9 6 3]]


In [12]:
array_2d=tf.constant(array_2d)
print(array_2d)

tf.Tensor(
[[7 4 1]
 [8 5 2]
 [9 6 3]], shape=(3, 3), dtype=int64)


In [13]:
array_se=np.array([(1,4,7),(2,5,8),(3,6,9)])
array_se=tf.constant(array_se)
print(array_se)

tf.Tensor(
[[1 4 7]
 [2 5 8]
 [3 6 9]], shape=(3, 3), dtype=int64)


In [14]:
matrix_sum=tf.add(array_2d,array_se)
print(matrix_sum)

tf.Tensor(
[[ 8  8  8]
 [10 10 10]
 [12 12 12]], shape=(3, 3), dtype=int64)


In [15]:
!pip install tensorflow